### ISSUE TITLE
`Client Semgrep: connection to server is erroring. Shutting down server.`

### ISSUE THREAD

**Issue by joeriddles** [semgrep/semgrep-vscode#58]
When I open a VS Code environment that uses Dev Containers, this is the output from the Semgrep extension:

```
[Error - 9:36:44 PM] Client Semgrep: connection to server is erroring. Shutting down server.
[Error - 9:36:44 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Wd.shutdown (/home/user/.vscode-server/extensions/semgrep.semgrep-1.4.1/out/main.js:39:8615)
	at Wd.stop (/home/user/.vscode-server/extensions/semgrep.semgrep-1.4.1/out/main.js:39:8194)
	at Wd.stop (/home/user/.vscode-server/extensions/semgrep.semgrep-1.4.1/out/main.js:39:27204)
	at Wd.handleConnectionError (/home/user/.vscode-server/extensions/semgrep.semgrep-1.4.1/out/main.js:39:13955)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ajbt200128** [comment]
closing as stale
